Repository KhronosGroup/Vulkan-Profiles, pull requests merged in 2022-01, with the labels that each got.

#18 docs: add missing queue properties
  OVERVIEW.md
Labels: bug, documentation, OS - Platform Independent, P3

#22 Bug fix for debug output and queueFlags
  PROFILES.md
  library/include/vulkan/debug/vulkan_profiles.hpp
  library/include/vulkan/vulkan_profiles.hpp
  library/scripts/genvp.py
  library/source/debug/vulkan_profiles.cpp
  library/source/vulkan_profiles.cpp
Labels: bug, OS - Platform Independent, P0 - Must Fix

#23 layer: validate all test profile files in a dedicated test
  CMakeLists.txt
  layer/tests/CMakeLists.txt
  layer/tests/profiles_test_helper.cpp
  layer/tests/tests.cpp
  layer/tests/tests_promoted.cpp
  profiles/test/data/VP_LUNARG_test_formats.json
  profiles/test/test_validate.cpp
Labels: enhancement, OS - Platform Independent, P2

#27 layer: jump to BETA status
  layer/VkLayer_khronos_profiles.json.in
Labels: enhancement, OS - Platform Independent, P3

#24 Fix TrimPrefix early assert in vk_layer_settings.cpp (vku)
  vku/vk_layer_settings.cpp
Labels: bug, OS - Platform Independent, P1

#29 profiles layer: Remove append macro
  layer/profiles.cpp
Labels: enhancement, OS - Platform Independent, P3

#30 Android Profiles API Library unit test
  library/test/CMakeLists.txt
  library/test/test_api_create_device_android.cpp
Labels: enhancement, OS - Android, P0 - Must Fix

#32 profiles layer: Update documentation and set default values
  layer/TUTORIAL.md
  layer/profiles.cpp
Labels: documentation, OS - Platform Independent, P2

#39 Add legends to the generated documentation tables
  PROFILES.md
  library/scripts/genvp.py
Labels: documentation, OS - Platform Independent, P0 - Must Fix

#44 docs: clarify Vulkan requirements
  OVERVIEW.md
Labels: documentation, OS - Platform Independent, P1

#35 Various layer issues encountered during Android port
  layer/profiles.cpp
Labels: bug, OS - Android, P0 - Must Fix

#26 Changed vku dir name to layer-utils
  CMakeLists.txt
  layer-utils/CMakeLists.txt
  layer-utils/vk_layer_settings.cpp
  layer-utils/vk_layer_settings.h
  layer/CMakeLists.txt
  layer/profiles.cpp
Labels: enhancement

#55 profiles layer: Update tutorial
  layer/TUTORIAL.md
Labels: documentation, OS - Platform Independent, P1

#50 Profiles doc - add man page links and fix bugs
  PROFILES.md
  library/scripts/genvp.py
Labels: bug, documentation, enhancement, OS - Platform Independent, P0 - Must Fix

#45 Add debug message containing device/driver info
  library/include/vulkan/debug/vulkan_profiles.hpp
  library/scripts/genvp.py
  library/source/debug/vulkan_profiles.cpp
  library/test/test_mocked_api_get_physdev_profile_support.cpp
Labels: enhancement, OS - Platform Independent, P2

#60 Docs overview
  OVERVIEW.md
Labels: documentation, OS - Platform Independent, P2
