Repository KhronosGroup/Vulkan-Profiles, pull requests merged in 2022-11, with the labels that each got.

#316 profile: fix roadmap 2022 maxInlineUniformTotalSize limit
  profiles/VP_KHR_roadmap_2022.json
Labels: bug, OS - Platform Independent, P0 - Must Fix

#317 profiles: pull Roadmap 2022 profiles from Vulkan-Header repository
  .gitignore
  profiles/VP_KHR_roadmap_2022.json
  scripts/CMakeLists.txt
Labels: enhancement, OS - Platform Independent, P1

#315 profile: Vulkan baseline profiles proposal
  profiles/test/data/VP_KHR_baseline.json
  profiles/test/test_validate.cpp
Labels: enhancement, OS - Platform Independent, P1

#320 Updated to more secure vsnprintf to fix deprecation errors with Apple…
  layer-utils/vk_layer_settings.cpp
  profiles/test/test_validate.cpp
  scripts/gen_profiles_layer.py
Labels: OS - macOS

#328 cmake: remove dead stuff
  CMakeLists.txt
  generator/CMakeLists.txt
  generator/external/compat/optional.hpp
  generator/external/generated-jsoncpp/json/json-forwards.h
  generator/external/generated-jsoncpp/json/json.h
  generator/external/generated-jsoncpp/jsoncpp.cpp
  generator/external/valijson/LICENSE
  generator/external/valijson/adapters/adapter.hpp
  generator/external/valijson/adapters/basic_adapter.hpp
  generator/external/valijson/adapters/boost_json_adapter.hpp
  generator/external/valijson/adapters/frozen_value.hpp
  generator/external/valijson/adapters/json11_adapter.hpp
  generator/external/valijson/adapters/jsoncpp_adapter.hpp
  generator/external/valijson/adapters/nlohmann_json_adapter.hpp
  generator/external/valijson/adapters/picojson_adapter.hpp
  generator/external/valijson/adapters/poco_json_adapter.hpp
  generator/external/valijson/adapters/property_tree_adapter.hpp
  generator/external/valijson/adapters/qtjson_adapter.hpp
  generator/external/valijson/adapters/rapidjson_adapter.hpp
  generator/external/valijson/adapters/std_string_adapter.hpp
  generator/external/valijson/adapters/yaml_cpp_adapter.hpp
  generator/external/valijson/constraint_builder.hpp
  generator/external/valijson/constraints/basic_constraint.hpp
  generator/external/valijson/constraints/concrete_constraints.hpp
  generator/external/valijson/constraints/constraint.hpp
  generator/external/valijson/constraints/constraint_visitor.hpp
  generator/external/valijson/exceptions.hpp
  generator/external/valijson/internal/adapter.hpp
  generator/external/valijson/internal/basic_adapter.hpp
  generator/external/valijson/internal/custom_allocator.hpp
  generator/external/valijson/internal/debug.hpp
  generator/external/valijson/internal/frozen_value.hpp
  generator/external/valijson/internal/json_pointer.hpp
  generator/external/valijson/internal/json_reference.hpp
  generator/external/valijson/internal/optional.hpp
  generator/external/valijson/internal/optional_bundled.hpp
  generator/external/valijson/internal/uri.hpp
  generator/external/valijson/schema.hpp
  generator/external/valijson/schema_parser.hpp
  generator/external/valijson/subschema.hpp
  generator/external/valijson/utils/boost_json_utils.hpp
  generator/external/valijson/utils/file_utils.hpp
  generator/external/valijson/utils/json11_utils.hpp
  generator/external/valijson/utils/jsoncpp_utils.hpp
  generator/external/valijson/utils/nlohmann_json_utils.hpp
  generator/external/valijson/utils/picojson_utils.hpp
  generator/external/valijson/utils/poco_json_utils.hpp
  generator/external/valijson/utils/property_tree_utils.hpp
  generator/external/valijson/utils/qtjson_utils.hpp
  generator/external/valijson/utils/rapidjson_utils.hpp
  generator/external/valijson/utils/utf8_utils.hpp
  generator/external/valijson/utils/yaml_cpp_utils.hpp
  generator/external/valijson/validation_results.hpp
  generator/external/valijson/validation_visitor.hpp
  generator/external/valijson/validator.hpp
  generator/generator.cpp
  generator/generator.hpp
  generator/test/CMakeLists.txt
  generator/test/test_util.cpp
Labels: enhancement, OS - Platform Independent, P1

#329 cmake: set CXX standard uniformaly
  CMakeLists.txt
Labels: enhancement, OS - Platform Independent, P2
