Repository KhronosGroup/Vulkan-Profiles, pull requests merged in 2022-02, with the labels that each got.

#63 Move generator script out of library subdirectory
  CMakeLists.txt
  library/CMakeLists.txt
  library/test/CMakeLists.txt
  scripts/CMakeLists.txt
  scripts/genvp.py
Labels: enhancement, OS - Platform Independent

#66 docs: overview docs feedback
  OVERVIEW.md
Labels: documentation, OS - Platform Independent, P2

#65 profiles layer tutorial: Warn about using multiple versions of same structure
  layer/TUTORIAL.md
Labels: documentation, OS - Platform Independent, P2

#69 layer: fix missing macos preset entry
  layer/VkLayer_khronos_profiles.json.in
Labels: bug, OS - macOS, P0 - Must Fix

#70 Layer: fix schema validation
  layer/VkLayer_khronos_profiles.json.in
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P1

#74 profiles layer: Print all warnings before failing
  layer/profiles.cpp
Labels: enhancement, OS - Platform Independent, P1

#80 profiles layer: Add GetPhysDev2 extensions of not present
  layer/TUTORIAL.md
  layer/profiles.cpp
  layer/tests/tests.cpp
Labels: bug, enhancement, OS - Platform Independent, P1

#86 profiles layer: Fix duplicated ShaderDrawParametersFeatures warning
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P3

#84 profiles layer: Fix checking vk version
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P1

#85 profiles layer: Add missing line breaks to log messages
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P2

#88 layer: fix CreateInstance extension list creation
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P0 - Must Fix

#89 profiles layer: Use correct version of GetPhysicalDeviceFormatProperties2
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P0 - Must Fix

#90 Use log print by default for library debug messages on Android
  library/include/vulkan/debug/vulkan_profiles.hpp
  library/source/debug/vulkan_profiles.cpp
  scripts/genvp.py
Labels: enhancement, OS - Android, P1

#92 layer: implement default value for profile_name setting
  layer/VkLayer_khronos_profiles.json.in
  layer/profiles.cpp
  layer/profiles.h
Labels: bug, OS - Platform Independent, P0 - Must Fix

#93 layer: DrawParameter bugfixing
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P2

#94 Warn on Vulkan Instance and Profile API version mismatch
  layer/profiles.cpp
Labels: bug, enhancement, OS - Platform Independent, P2

#98 profiles layer: Improve message logs for profile and device values
  layer/profiles.cpp
Labels: enhancement, OS - Platform Independent, P3

#102 profiles layer: Improve log messages
  layer/profiles.cpp
Labels: enhancement, OS - Platform Independent, P3

#105 docs: Bob review fixes
  OVERVIEW.md
Labels: documentation, OS - Platform Independent, P2

#109 profiles layer: Remove unused simulate format properties bit
  layer/profiles.h
  layer/tests/profiles_test_helper.cpp
Labels: enhancement, OS - Platform Independent, P3

#61 Create Android test package for `VpLibrary_test_api_create_device_android`
  library/test/CMakeLists.txt
  library/test/platforms/android/AndroidManifest.xml
  library/test/platforms/android/res/values/strings.xml
Labels: OS - Android, P0 - Must Fix, test

#111 layer: clear displayed name for the flag
  layer/VkLayer_khronos_profiles.json.in
Labels: enhancement, OS - Platform Independent, P3

#114 profiles layer: Fix debug logging parsed structs
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P3

#117 profiles layer: Skip loading structs from excluded extensions
  layer/profiles.cpp
  layer/tests/tests.cpp
Labels: bug, enhancement, OS - Platform Independent, P1

#119 layer: override the requested API version, min vk version is 1.1
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P1

#125 profiles layer: Make missing extension logs more clear
  layer/profiles.cpp
Labels: enhancement, OS - Platform Independent, P2

#124 profiles layer: Remove log left over from debugging
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P3

#122 profiles layer: Update docs api requirement
  layer/TUTORIAL.md
Labels: documentation, OS - Platform Independent, P3

#123 profiles layer: Fix validation requested api version
  layer/profiles.cpp
Labels: bug, OS - Platform Independent, P2

#128 Fix JSON schema profile name matching
  schema/profile_schema.json
  scripts/genvp.py
Labels: bug, OS - Platform Independent, P1

#131 profile: remove descriptorBindingUniformBufferUpdateAfterBind from roadmap 2022
  PROFILES.md
  library/include/vulkan/debug/vulkan_profiles.hpp
  library/include/vulkan/vulkan_profiles.hpp
  library/source/debug/vulkan_profiles.cpp
  library/source/vulkan_profiles.cpp
  profiles/VP_KHR_roadmap_2022.json
Labels: enhancement, OS - Platform Independent, P1

#136 profile: improve API version dependences
  PROFILES.md
  library/include/vulkan/debug/vulkan_profiles.h
  library/include/vulkan/debug/vulkan_profiles.hpp
  library/include/vulkan/vulkan_profiles.h
  library/include/vulkan/vulkan_profiles.hpp
  profiles/VP_ANDROID_baseline_2021.json
  profiles/VP_LUNARG_desktop_portability_2021.json
Labels: documentation, OS - Platform Independent, P2

#129 Fix and improve queue family matching in library
  library/include/vulkan/debug/vulkan_profiles.hpp
  library/include/vulkan/vulkan_profiles.hpp
  library/source/debug/vulkan_profiles.cpp
  library/source/vulkan_profiles.cpp
  scripts/genvp.py
Labels: bug, OS - Platform Independent, P0 - Must Fix

#137 Auto-generate schema version from header version
  schema/profile_schema.json
  scripts/genvp.py
Labels: bug, OS - Platform Independent, P2

#134 Use tag v1.3.204
  CMakeLists.txt
Labels: documentation, OS - Platform Independent, P2

#141 Fix json file path settings in layer tests.cpp
  layer/tests/tests.cpp
Labels: bug

#150 profile: allow generating schema for API 1.2.203
  scripts/genvp.py
Labels: enhancement, OS - Platform Independent, P2

#158 Fix const array size handling in lambda generators
  scripts/genvp.py
Labels: bug, OS - Platform Independent
