Repository KhronosGroup/Vulkan-Profiles, pull requests merged in 2023-08, with the labels that each got.

#472 layer: fix error message typo
  CHANGELOG.md
  layer/VkLayer_khronos_profiles.json.in
  scripts/gen_profiles_layer.py
Labels: bug, documentation, OS - Platform Independent, P2

#473 layer: fix layer settings tests
  layer/tests/tests.cpp
  layer/tests/tests_combine_intersection.cpp
  layer/tests/tests_combine_union.cpp
  layer/tests/tests_mechanism.cpp
  layer/tests/tests_mechanism_api_version.cpp
  layer/tests/tests_mechanism_check_values.cpp
  layer/tests/tests_mechanism_format.cpp
  scripts/gen_profiles_tests.py
  scripts/known_good.json
Labels: bug, OS - Platform Independent, P0 - Must Fix

#474 layer: Fix query of capabilities of aliased extensions
  CHANGELOG.md
  scripts/gen_profiles_layer.py
Labels: bug, OS - Platform Independent, P1

#478 build: Use utility libraries vk_enum_string_helper.h
  layer/profiles_util.h
  scripts/known_good.json
Labels: enhancement, OS - Platform Independent, P1

#477 scripts: Improve handling of API variants
  scripts/gen_profiles_layer.py
  scripts/gen_profiles_solution.py
Labels: enhancement, OS - Platform Independent, P1

#483 layer: Fix API stype naming
  layer/tests/profiles_test_helper.cpp
  scripts/known_good.json
Labels: bug, OS - Platform Independent, P1
