Repository KhronosGroup/Vulkan-Profiles, pull requests merged in 2023-10, with the labels that each got.

#511 docs: New SDK branch convention
  README.md
Labels: documentation

#520 Require Android baseline 2021 profile in Android baseline 2022 profile by reference instead of copying the capabilities
  profiles/VP_ANDROID_baseline_2022.json
Labels: enhancement, OS - Platform Independent, P2

#527 library: Add test profiles requiring profiles
  library/test/CMakeLists.txt
  library/test/test_mocked_api_create_device_profile_requirement.cpp
  library/test/test_mocked_api_get_physdev_profile_support.cpp
  profiles/test/CMakeLists.txt
  profiles/test/data/VP_LUNARG_test_profile_requirements/VP_LUNARG_test_profile_a.json
  profiles/test/data/VP_LUNARG_test_profile_requirements/VP_LUNARG_test_profile_b.json
  profiles/test/data/VP_LUNARG_test_profile_requirements/vulkan_profiles.cpp
  profiles/test/data/VP_LUNARG_test_profile_requirements/vulkan_profiles.h
  profiles/test/data/VP_LUNARG_test_profile_requirements/vulkan_profiles.hpp
  scripts/gen_profiles_layer.py
  scripts/gen_profiles_solution.py
Labels: enhancement, OS - Platform Independent, P1, test
