Repository KhronosGroup/Vulkan-Profiles, pull requests merged in 2023-04, with the labels that each got.

#396 Fix invalid message when trying to override a supported capability to…
  scripts/gen_profiles_layer.py
Labels: bug, OS - Platform Independent, P2

#397 layer: add setting to control vulkan feature init
  CHANGELOG.md
  layer/VkLayer_khronos_profiles.json.in
  layer/profiles.h
  layer/tests/tests_mechanism.cpp
  scripts/gen_profiles_layer.py
Labels: enhancement, OS - Platform Independent, P1

#398 doc: fix schema link
  layer/TUTORIAL.md
Labels: bug, OS - Platform Independent, P2

#400 layer: add support of multiple variants
  CHANGELOG.md
  CMakeLists.txt
  layer/profiles.h
  layer/tests/tests_mechanism.cpp
  profiles/test/data/VP_LUNARG_test_variants.json
  scripts/gen_profiles_layer.py
Labels: bug, enhancement, OS - Platform Independent, P1

#402 cmake: Fix WIN32 installation
  layer/CMakeLists.txt
Labels: OS - Windows

#410 layer: add force physical device setting
  layer/VkLayer_khronos_profiles.json.in
  layer/profiles_settings.cpp
  layer/profiles_settings.h
  layer/profiles_util.cpp
  layer/profiles_util.h
  layer/tests/tests_mechanism.cpp
  scripts/gen_profiles_layer.py
Labels: enhancement, OS - Platform Independent, P2

#411 layer: fix invalid message when using multiple GPUs
  scripts/gen_profiles_layer.py
Labels: bug, OS - Platform Independent, P2

#412 layer: notify disabled force gpu on system with 1 GPU
  scripts/gen_profiles_layer.py
Labels: enhancement, OS - Platform Independent, P3

#413 layer: Add force device preset
  layer/VkLayer_khronos_profiles.json.in
Labels: enhancement, OS - Platform Independent, P2
